sudo: required
# We need the systemd for the kubeadm and it's default from 16.04+
dist: xenial
services:
- docker
language: go
go:
  - "1.11.x"

stages:
  - Unit test
  - Acceptance test

jobs:
  include:
    - name: Unit test
      stage: Unit test
      install:
        # This script is used by the Travis build to install a cookie for
        # go.googlesource.com so rate limits are higher when using `go get` to fetch
        # packages that live there.
        # See: https://github.com/golang/go/issues/12933
        - bash scripts/gogetcookie.sh
        - go get github.com/kardianos/govendor
      script:
        - make test
        - make vendor-status
        - make vet
        - make website-test
    - name: Acceptance test
      stage: Acceptance test
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
        - KUBERNETES_VERSION=v1.10.0
      install:
        - sudo apt-get update
        - sudo apt-get install -y socat
      before_script:
        - sudo mount --make-rshared /
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64/kubectl
        - sudo chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 
        - sudo chmod +x minikube && sudo mv minikube /usr/local/bin/
        - sudo minikube start --vm-driver=none --kubernetes-version=${KUBERNETES_VERSION}
        - minikube update-context
        - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
        - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
        - chmod 700 get_helm.sh
        - DESIRED_VERSION=v2.11.0 ./get_helm.sh
      script:
        # needed till we fix the init in the provider
        - helm init --client-only
        - travis_wait 60 make testacc

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
